name: Bump version and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get last commit message
        id: get_commit
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Decide version part to bump
        id: decide_bump
        run: |
          echo "Commit message: $COMMIT_MSG"
          if echo "$COMMIT_MSG" | grep -qi 'bump: major'; then
            echo "version_part=major" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MSG" | grep -qi 'bump: minor'; then
            echo "version_part=minor" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MSG" | grep -qi 'bump: patch'; then
            echo "version_part=patch" >> $GITHUB_OUTPUT
          else
            echo "version_part=none" >> $GITHUB_OUTPUT
          fi

      - name: Install bumpversion
        if: steps.decide_bump.outputs.version_part != 'none'
        run: pip install bumpversion

      - name: Bump version
        if: steps.decide_bump.outputs.version_part != 'none'
        run: bumpversion ${{ steps.decide_bump.outputs.version_part }} --allow-dirty
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com

      - name: Push bump commit and tags
        if: steps.decide_bump.outputs.version_part != 'none'
        run: |
          git push origin m
